// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfrwzgyzszhzkbwcuimb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcnd6Z3l6c3poemtid2N1aW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjEzOTEsImV4cCI6MjA2NjMzNzM5MX0.A5DgTfp3xEA-RlMLUa-yyLZqgbLR_jYaBjhk2kBkicA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);